import { Match, Team } from './types';

// Fallback visuel plus propre (Bouclier générique) au lieu de l'avatar texte
export const getLogo = (name: string) => `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent(name)}&backgroundColor=1e293b&textColor=ffffff&chars=1`;

export const LEAGUES = [
    'Ligue 1', 
    'Premier League', 
    'La Liga', 
    'Serie A', 
    'Bundesliga', 
    'Champions League', 
    'Europa League',
    'Eredivisie', 
    'Liga NOS'
];

// VRAIS LOGOS (Sources Wikimedia/CDN stables)
export const REAL_TEAM_LOGOS: Record<string, string> = {
  // --- FRANCE (Ligue 1) ---
  "psg": "https://upload.wikimedia.org/wikipedia/fr/thumb/8/86/Paris_Saint-Germain_Logo.svg/1024px-Paris_Saint-Germain_Logo.svg.png",
  "parissaintgermain": "https://upload.wikimedia.org/wikipedia/fr/thumb/8/86/Paris_Saint-Germain_Logo.svg/1024px-Paris_Saint-Germain_Logo.svg.png",
  "paris": "https://upload.wikimedia.org/wikipedia/fr/thumb/8/86/Paris_Saint-Germain_Logo.svg/1024px-Paris_Saint-Germain_Logo.svg.png",
  "om": "https://upload.wikimedia.org/wikipedia/fr/thumb/4/43/Logo_Olympique_de_Marseille.svg/1200px-Logo_Olympique_de_Marseille.svg.png",
  "marseille": "https://upload.wikimedia.org/wikipedia/fr/thumb/4/43/Logo_Olympique_de_Marseille.svg/1200px-Logo_Olympique_de_Marseille.svg.png",
  "olympiquedemarseille": "https://upload.wikimedia.org/wikipedia/fr/thumb/4/43/Logo_Olympique_de_Marseille.svg/1200px-Logo_Olympique_de_Marseille.svg.png",
  "ol": "https://upload.wikimedia.org/wikipedia/fr/thumb/8/86/Olympique_Lyonnais_-_Logo_2022.svg/1200px-Olympique_Lyonnais_-_Logo_2022.svg.png",
  "lyon": "https://upload.wikimedia.org/wikipedia/fr/thumb/8/86/Olympique_Lyonnais_-_Logo_2022.svg/1200px-Olympique_Lyonnais_-_Logo_2022.svg.png",
  "olympiquelyonnais": "https://upload.wikimedia.org/wikipedia/fr/thumb/8/86/Olympique_Lyonnais_-_Logo_2022.svg/1200px-Olympique_Lyonnais_-_Logo_2022.svg.png",
  "monaco": "https://upload.wikimedia.org/wikipedia/fr/thumb/e/e2/AS_Monaco_FC_2021.svg/1200px-AS_Monaco_FC_2021.svg.png",
  "asmonaco": "https://upload.wikimedia.org/wikipedia/fr/thumb/e/e2/AS_Monaco_FC_2021.svg/1200px-AS_Monaco_FC_2021.svg.png",
  "losc": "https://upload.wikimedia.org/wikipedia/fr/thumb/6/62/Logo_LOSC_Lille_2018.svg/1200px-Logo_LOSC_Lille_2018.svg.png",
  "lille": "https://upload.wikimedia.org/wikipedia/fr/thumb/6/62/Logo_LOSC_Lille_2018.svg/1200px-Logo_LOSC_Lille_2018.svg.png",
  "losclille": "https://upload.wikimedia.org/wikipedia/fr/thumb/6/62/Logo_LOSC_Lille_2018.svg/1200px-Logo_LOSC_Lille_2018.svg.png",
  "lens": "https://upload.wikimedia.org/wikipedia/fr/thumb/2/26/Racing_Club_de_Lens_2025_logo.svg/1200px-Racing_Club_de_Lens_2025_logo.svg.png",
  "rclens": "https://upload.wikimedia.org/wikipedia/fr/thumb/2/26/Racing_Club_de_Lens_2025_logo.svg/1200px-Racing_Club_de_Lens_2025_logo.svg.png",
  "racingclubdelens": "https://upload.wikimedia.org/wikipedia/fr/thumb/2/26/Racing_Club_de_Lens_2025_logo.svg/1200px-Racing_Club_de_Lens_2025_logo.svg.png",
  "rennes": "https://upload.wikimedia.org/wikipedia/fr/thumb/e/e9/Logo_Stade_Rennais_FC.svg/1200px-Logo_Stade_Rennais_FC.svg.png",
  "staderennais": "https://upload.wikimedia.org/wikipedia/fr/thumb/e/e9/Logo_Stade_Rennais_FC.svg/1200px-Logo_Stade_Rennais_FC.svg.png",
  "nice": "https://upload.wikimedia.org/wikipedia/fr/thumb/b/b1/Logo_OGC_Nice_2013.svg/1200px-Logo_OGC_Nice_2013.svg.png",
  "ogcnice": "https://upload.wikimedia.org/wikipedia/fr/thumb/b/b1/Logo_OGC_Nice_2013.svg/1200px-Logo_OGC_Nice_2013.svg.png",
  "brest": "https://upload.wikimedia.org/wikipedia/fr/thumb/1/14/Stade_Brestois_29_2010.svg/1200px-Stade_Brestois_29_2010.svg.png",
  "stadebrestois": "https://upload.wikimedia.org/wikipedia/fr/thumb/1/14/Stade_Brestois_29_2010.svg/1200px-Stade_Brestois_29_2010.svg.png",
  "stadebrestois29": "https://upload.wikimedia.org/wikipedia/fr/thumb/1/14/Stade_Brestois_29_2010.svg/1200px-Stade_Brestois_29_2010.svg.png",
  "reims": "https://upload.wikimedia.org/wikipedia/fr/thumb/0/06/Stade_de_Reims_logo_2020.svg/1200px-Stade_de_Reims_logo_2020.svg.png",
  "stadedereims": "https://upload.wikimedia.org/wikipedia/fr/thumb/0/06/Stade_de_Reims_logo_2020.svg/1200px-Stade_de_Reims_logo_2020.svg.png",
  "strasbourg": "https://upload.wikimedia.org/wikipedia/fr/thumb/9/91/Racing_Club_de_Strasbourg_Alsace_logo_2016.svg/1200px-Racing_Club_de_Strasbourg_Alsace_logo_2016.svg.png",
  "rcstrasbourg": "https://upload.wikimedia.org/wikipedia/fr/thumb/9/91/Racing_Club_de_Strasbourg_Alsace_logo_2016.svg/1200px-Racing_Club_de_Strasbourg_Alsace_logo_2016.svg.png",
  "nantes": "https://upload.wikimedia.org/wikipedia/fr/thumb/2/2b/FC_Nantes_2019_logo.svg/1200px-FC_Nantes_2019_logo.svg.png",
  "fcnantes": "https://upload.wikimedia.org/wikipedia/fr/thumb/2/2b/FC_Nantes_2019_logo.svg/1200px-FC_Nantes_2019_logo.svg.png",
  "montpellier": "https://upload.wikimedia.org/wikipedia/fr/thumb/a/a8/Montpellier_H%C3%A9rault_Sport_Club_Logo.svg/1200px-Montpellier_H%C3%A9rault_Sport_Club_Logo.svg.png",
  "mhsc": "https://upload.wikimedia.org/wikipedia/fr/thumb/a/a8/Montpellier_H%C3%A9rault_Sport_Club_Logo.svg/1200px-Montpellier_H%C3%A9rault_Sport_Club_Logo.svg.png",
  "toulouse": "https://upload.wikimedia.org/wikipedia/fr/thumb/8/8b/Toulouse_FC_2018_logo.svg/1200px-Toulouse_FC_2018_logo.svg.png",
  "toulousefc": "https://upload.wikimedia.org/wikipedia/fr/thumb/8/8b/Toulouse_FC_2018_logo.svg/1200px-Toulouse_FC_2018_logo.svg.png",
  "tefece": "https://upload.wikimedia.org/wikipedia/fr/thumb/8/8b/Toulouse_FC_2018_logo.svg/1200px-Toulouse_FC_2018_logo.svg.png",
  "lehavre": "https://upload.wikimedia.org/wikipedia/fr/thumb/6/63/Le_Havre_Athletic_Club_2012_logo.svg/1200px-Le_Havre_Athletic_Club_2012_logo.svg.png",
  "hac": "https://upload.wikimedia.org/wikipedia/fr/thumb/6/63/Le_Havre_Athletic_Club_2012_logo.svg/1200px-Le_Havre_Athletic_Club_2012_logo.svg.png",
  "metz": "https://upload.wikimedia.org/wikipedia/fr/thumb/4/4a/FC_Metz_2021.svg/1200px-FC_Metz_2021.svg.png",
  "fcmetz": "https://upload.wikimedia.org/wikipedia/fr/thumb/4/4a/FC_Metz_2021.svg/1200px-FC_Metz_2021.svg.png",
  "lorient": "https://upload.wikimedia.org/wikipedia/fr/thumb/1/1d/FC_Lorient_logo_2023.svg/1200px-FC_Lorient_logo_2023.svg.png",
  "fclorient": "https://upload.wikimedia.org/wikipedia/fr/thumb/1/1d/FC_Lorient_logo_2023.svg/1200px-FC_Lorient_logo_2023.svg.png",
  "auxerre": "https://upload.wikimedia.org/wikipedia/fr/thumb/6/61/Logo_AJ_Auxerre.svg/1200px-Logo_AJ_Auxerre.svg.png",
  "ajauxerre": "https://upload.wikimedia.org/wikipedia/fr/thumb/6/61/Logo_AJ_Auxerre.svg/1200px-Logo_AJ_Auxerre.svg.png",
  "saintetienne": "https://upload.wikimedia.org/wikipedia/fr/thumb/9/98/Logo_AS_Saint-%C3%89tienne_2022.svg/1200px-Logo_AS_Saint-%C3%89tienne_2022.svg.png",
  "assaintetienne": "https://upload.wikimedia.org/wikipedia/fr/thumb/9/98/Logo_AS_Saint-%C3%89tienne_2022.svg/1200px-Logo_AS_Saint-%C3%89tienne_2022.svg.png",
  "asse": "https://upload.wikimedia.org/wikipedia/fr/thumb/9/98/Logo_AS_Saint-%C3%89tienne_2022.svg/1200px-Logo_AS_Saint-%C3%89tienne_2022.svg.png",
  
  // --- ANGLETERRE (Premier League) ---
  "mancity": "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/1200px-Manchester_City_FC_badge.svg.png",
  "manchestercity": "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/1200px-Manchester_City_FC_badge.svg.png",
  "mci": "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/1200px-Manchester_City_FC_badge.svg.png",
  "arsenal": "https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Arsenal_FC.svg/1200px-Arsenal_FC.svg.png",
  "ars": "https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Arsenal_FC.svg/1200px-Arsenal_FC.svg.png",
  "liverpool": "https://upload.wikimedia.org/wikipedia/fr/thumb/5/54/Logo_FC_Liverpool.svg/1200px-Logo_FC_Liverpool.svg.png",
  "liv": "https://upload.wikimedia.org/wikipedia/fr/thumb/5/54/Logo_FC_Liverpool.svg/1200px-Logo_FC_Liverpool.svg.png",
  "manutd": "https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/1200px-Manchester_United_FC_crest.svg.png",
  "manchesterunited": "https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/1200px-Manchester_United_FC_crest.svg.png",
  "mune": "https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/1200px-Manchester_United_FC_crest.svg.png",
  "chelsea": "https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Chelsea_FC.svg/1200px-Chelsea_FC.svg.png",
  "tottenham": "https://upload.wikimedia.org/wikipedia/fr/thumb/5/5c/Logo_Tottenham_Hotspur.svg/626px-Logo_Tottenham_Hotspur.svg.png",
  "tottenhamhotspur": "https://upload.wikimedia.org/wikipedia/fr/thumb/5/5c/Logo_Tottenham_Hotspur.svg/626px-Logo_Tottenham_Hotspur.svg.png",
  "astonvilla": "https://upload.wikimedia.org/wikipedia/fr/thumb/6/67/Logo_Aston_Villa_FC_2016.svg/1200px-Logo_Aston_Villa_FC_2016.svg.png",
  "newcastle": "https://upload.wikimedia.org/wikipedia/fr/thumb/6/63/Newcastle_United_Logo.svg/1200px-Newcastle_United_Logo.svg.png",
  "newcastleunited": "https://upload.wikimedia.org/wikipedia/fr/thumb/6/63/Newcastle_United_Logo.svg/1200px-Newcastle_United_Logo.svg.png",
  "westham": "https://upload.wikimedia.org/wikipedia/en/thumb/c/c2/West_Ham_United_FC_logo.svg/1200px-West_Ham_United_FC_logo.svg.png",
  "westhamunited": "https://upload.wikimedia.org/wikipedia/en/thumb/c/c2/West_Ham_United_FC_logo.svg/1200px-West_Ham_United_FC_logo.svg.png",
  "brighton": "https://upload.wikimedia.org/wikipedia/en/thumb/f/fd/Brighton_%26_Hove_Albion_logo.svg/1200px-Brighton_%26_Hove_Albion_logo.svg.png",
  "wolves": "https://upload.wikimedia.org/wikipedia/en/thumb/f/fc/Wolverhampton_Wanderers.svg/1200px-Wolverhampton_Wanderers.svg.png",
  "wolverhampton": "https://upload.wikimedia.org/wikipedia/en/thumb/f/fc/Wolverhampton_Wanderers.svg/1200px-Wolverhampton_Wanderers.svg.png",
  "everton": "https://upload.wikimedia.org/wikipedia/en/thumb/7/7c/Everton_FC_logo.svg/1200px-Everton_FC_logo.svg.png",
  "fulham": "https://upload.wikimedia.org/wikipedia/fr/thumb/d/d0/Logo_Fulham_FC.svg/1200px-Logo_Fulham_FC.svg.png",
  "crystalpalace": "https://upload.wikimedia.org/wikipedia/fr/thumb/0/0c/Crystal_Palace_FC_logo.svg/1200px-Crystal_Palace_FC_logo.svg.png",

  // --- ESPAGNE (La Liga) ---
  "realmadrid": "https://upload.wikimedia.org/wikipedia/fr/thumb/c/c7/Logo_Real_Madrid.svg/1200px-Logo_Real_Madrid.svg.png",
  "real": "https://upload.wikimedia.org/wikipedia/fr/thumb/c/c7/Logo_Real_Madrid.svg/1200px-Logo_Real_Madrid.svg.png",
  "rma": "https://upload.wikimedia.org/wikipedia/fr/thumb/c/c7/Logo_Real_Madrid.svg/1200px-Logo_Real_Madrid.svg.png",
  "barcelona": "https://upload.wikimedia.org/wikipedia/fr/thumb/a/a1/Logo_FC_Barcelona.svg/1200px-Logo_FC_Barcelona.svg.png",
  "barca": "https://upload.wikimedia.org/wikipedia/fr/thumb/a/a1/Logo_FC_Barcelona.svg/1200px-Logo_FC_Barcelona.svg.png",
  "fcbarcelona": "https://upload.wikimedia.org/wikipedia/fr/thumb/a/a1/Logo_FC_Barcelona.svg/1200px-Logo_FC_Barcelona.svg.png",
  "atletico": "https://upload.wikimedia.org/wikipedia/fr/thumb/9/92/Logo_ATM_2017.svg/1200px-Logo_ATM_2017.svg.png",
  "atleticomadrid": "https://upload.wikimedia.org/wikipedia/fr/thumb/9/92/Logo_ATM_2017.svg/1200px-Logo_ATM_2017.svg.png",
  "sevilla": "https://upload.wikimedia.org/wikipedia/fr/thumb/f/f1/Logo_Sevilla_FC.svg/1200px-Logo_Sevilla_FC.svg.png",
  "sevillafc": "https://upload.wikimedia.org/wikipedia/fr/thumb/f/f1/Logo_Sevilla_FC.svg/1200px-Logo_Sevilla_FC.svg.png",
  "betis": "https://upload.wikimedia.org/wikipedia/fr/thumb/1/13/Real_betis_logo.svg/1200px-Real_betis_logo.svg.png",
  "realbetis": "https://upload.wikimedia.org/wikipedia/fr/thumb/1/13/Real_betis_logo.svg/1200px-Real_betis_logo.svg.png",
  "realsociedad": "https://upload.wikimedia.org/wikipedia/fr/thumb/f/f1/Real_Sociedad_logo.svg/1200px-Real_Sociedad_logo.svg.png",
  "athleticbilbao": "https://upload.wikimedia.org/wikipedia/fr/thumb/1/10/Athletic_Bilbao_logo.svg/1200px-Athletic_Bilbao_logo.svg.png",
  "bilbao": "https://upload.wikimedia.org/wikipedia/fr/thumb/1/10/Athletic_Bilbao_logo.svg/1200px-Athletic_Bilbao_logo.svg.png",
  "villarreal": "https://upload.wikimedia.org/wikipedia/fr/thumb/7/70/Villarreal_CF_logo.svg/1200px-Villarreal_CF_logo.svg.png",
  "valencia": "https://upload.wikimedia.org/wikipedia/fr/thumb/f/f4/Valencia_CF_logo.svg/1200px-Valencia_CF_logo.svg.png",
  "valenciafc": "https://upload.wikimedia.org/wikipedia/fr/thumb/f/f4/Valencia_CF_logo.svg/1200px-Valencia_CF_logo.svg.png",
  "girona": "https://upload.wikimedia.org/wikipedia/fr/thumb/b/b4/Girona_FC_Logo.svg/1200px-Girona_FC_Logo.svg.png",
  "celta": "https://upload.wikimedia.org/wikipedia/fr/thumb/b/b0/Celta_Vigo_logo.svg/1200px-Celta_Vigo_logo.svg.png",
  "celtavigo": "https://upload.wikimedia.org/wikipedia/fr/thumb/b/b0/Celta_Vigo_logo.svg/1200px-Celta_Vigo_logo.svg.png",

  // --- ITALIE (Serie A) ---
  "inter": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/FC_Internazionale_Milano_2021.svg/1200px-FC_Internazionale_Milano_2021.svg.png",
  "intermilan": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/FC_Internazionale_Milano_2021.svg/1200px-FC_Internazionale_Milano_2021.svg.png",
  "internazionale": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/FC_Internazionale_Milano_2021.svg/1200px-FC_Internazionale_Milano_2021.svg.png",
  "acmilan": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Logo_of_AC_Milan.svg/1200px-Logo_of_AC_Milan.svg.png",
  "milan": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Logo_of_AC_Milan.svg/1200px-Logo_of_AC_Milan.svg.png",
  "juventus": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Juventus_FC_2017_icon_%28black%29.svg/1200px-Juventus_FC_2017_icon_%28black%29.svg.png",
  "juve": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Juventus_FC_2017_icon_%28black%29.svg/1200px-Juventus_FC_2017_icon_%28black%29.svg.png",
  "napoli": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/SSC_Neapel.svg/1200px-SSC_Neapel.svg.png",
  "sscnapoli": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/SSC_Neapel.svg/1200px-SSC_Neapel.svg.png",
  "roma": "https://upload.wikimedia.org/wikipedia/fr/thumb/5/5f/Logo_AS_Roma_2013.svg/1200px-Logo_AS_Roma_2013.svg.png",
  "asroma": "https://upload.wikimedia.org/wikipedia/fr/thumb/5/5f/Logo_AS_Roma_2013.svg/1200px-Logo_AS_Roma_2013.svg.png",
  "lazio": "https://upload.wikimedia.org/wikipedia/fr/thumb/0/04/Logo_SS_Lazio.svg/1200px-Logo_SS_Lazio.svg.png",
  "sslazio": "https://upload.wikimedia.org/wikipedia/fr/thumb/0/04/Logo_SS_Lazio.svg/1200px-Logo_SS_Lazio.svg.png",
  "atalanta": "https://upload.wikimedia.org/wikipedia/fr/thumb/5/54/Atalanta_BC.svg/1200px-Atalanta_BC.svg.png",
  "fiorentina": "https://upload.wikimedia.org/wikipedia/fr/thumb/e/e0/ACF_Fiorentina_Logo_2022.svg/1200px-ACF_Fiorentina_Logo_2022.svg.png",
  "bologna": "https://upload.wikimedia.org/wikipedia/fr/thumb/8/87/Bologna_fc_1909.svg/1200px-Bologna_fc_1909.svg.png",
  "torino": "https://upload.wikimedia.org/wikipedia/fr/thumb/2/2e/Torino_FC_Logo.svg/1200px-Torino_FC_Logo.svg.png",

  // --- ALLEMAGNE (Bundesliga) ---
  "bayern": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg/1200px-FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg.png",
  "bayernmunich": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg/1200px-FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg.png",
  "fcbayern": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg/1200px-FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg.png",
  "dortmund": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Borussia_Dortmund_logo.svg/1200px-Borussia_Dortmund_logo.svg.png",
  "bvb": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Borussia_Dortmund_logo.svg/1200px-Borussia_Dortmund_logo.svg.png",
  "borussiadortmund": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Borussia_Dortmund_logo.svg/1200px-Borussia_Dortmund_logo.svg.png",
  "leverkusen": "https://upload.wikimedia.org/wikipedia/fr/thumb/9/98/Bayer_Leverkusen_Logo.svg/1200px-Bayer_Leverkusen_Logo.svg.png",
  "bayerleverkusen": "https://upload.wikimedia.org/wikipedia/fr/thumb/9/98/Bayer_Leverkusen_Logo.svg/1200px-Bayer_Leverkusen_Logo.svg.png",
  "leipzig": "https://upload.wikimedia.org/wikipedia/en/thumb/0/04/RB_Leipzig_2014_logo.svg/1200px-RB_Leipzig_2014_logo.svg.png",
  "rbleipzig": "https://upload.wikimedia.org/wikipedia/en/thumb/0/04/RB_Leipzig_2014_logo.svg/1200px-RB_Leipzig_2014_logo.svg.png",
  "stuttgart": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/VfB_Stuttgart_1893_Logo.svg/1200px-VfB_Stuttgart_1893_Logo.svg.png",
  "vfbstuttgart": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/VfB_Stuttgart_1893_Logo.svg/1200px-VfB_Stuttgart_1893_Logo.svg.png",
  "frankfurt": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Eintracht_Frankfurt_Logo.svg/1200px-Eintracht_Frankfurt_Logo.svg.png",
  "eintracht": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Eintracht_Frankfurt_Logo.svg/1200px-Eintracht_Frankfurt_Logo.svg.png",
  "eintrachtfrankfurt": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Eintracht_Frankfurt_Logo.svg/1200px-Eintracht_Frankfurt_Logo.svg.png",
  "wolfsburg": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Logo-VfL-Wolfsburg.svg/1200px-Logo-VfL-Wolfsburg.svg.png",
  "vflwolfsburg": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Logo-VfL-Wolfsburg.svg/1200px-Logo-VfL-Wolfsburg.svg.png",
  "monchengladbach": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Borussia_M%C3%B6nchengladbach_logo.svg/1200px-Borussia_M%C3%B6nchengladbach_logo.svg.png",
  "borussiamonchengladbach": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Borussia_M%C3%B6nchengladbach_logo.svg/1200px-Borussia_M%C3%B6nchengladbach_logo.svg.png",
  
  // --- AUTRES (Portugal, Pays-Bas, Monde) ---
  "benfica": "https://upload.wikimedia.org/wikipedia/fr/thumb/8/87/Benfica_Lisbonne_2014.svg/1200px-Benfica_Lisbonne_2014.svg.png",
  "porto": "https://upload.wikimedia.org/wikipedia/fr/thumb/f/f1/FC_Porto_2022.svg/1200px-FC_Porto_2022.svg.png",
  "fcporto": "https://upload.wikimedia.org/wikipedia/fr/thumb/f/f1/FC_Porto_2022.svg/1200px-FC_Porto_2022.svg.png",
  "sporting": "https://upload.wikimedia.org/wikipedia/fr/thumb/1/12/Logo_Sporting_Clube_de_Portugal.svg/1200px-Logo_Sporting_Clube_de_Portugal.svg.png",
  "sportingcp": "https://upload.wikimedia.org/wikipedia/fr/thumb/1/12/Logo_Sporting_Clube_de_Portugal.svg/1200px-Logo_Sporting_Clube_de_Portugal.svg.png",
  "braga": "https://upload.wikimedia.org/wikipedia/fr/thumb/b/b2/SC_Braga_Logo.svg/1200px-SC_Braga_Logo.svg.png",
  "ajax": "https://upload.wikimedia.org/wikipedia/fr/thumb/7/7b/Ajax_Amsterdam.svg/1200px-Ajax_Amsterdam.svg.png",
  "ajaxamsterdam": "https://upload.wikimedia.org/wikipedia/fr/thumb/7/7b/Ajax_Amsterdam.svg/1200px-Ajax_Amsterdam.svg.png",
  "psv": "https://upload.wikimedia.org/wikipedia/fr/thumb/1/15/PSV_Eindhoven.svg/1200px-PSV_Eindhoven.svg.png",
  "psveindhoven": "https://upload.wikimedia.org/wikipedia/fr/thumb/1/15/PSV_Eindhoven.svg/1200px-PSV_Eindhoven.svg.png",
  "feyenoord": "https://upload.wikimedia.org/wikipedia/fr/thumb/e/e0/Feyenoord_Rotterdam.svg/1200px-Feyenoord_Rotterdam.svg.png",
  "galatasaray": "https://upload.wikimedia.org/wikipedia/fr/thumb/3/36/Galatasaray_Logo.svg/1200px-Galatasaray_Logo.svg.png",
  "fenerbahce": "https://upload.wikimedia.org/wikipedia/fr/thumb/8/83/Fenerbahce_Spor_Kulubu.svg/1200px-Fenerbahce_Spor_Kulubu.svg.png",
  "besiktas": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Be%C5%9Fikta%C5%9F_Logo_BJK.svg/1200px-Be%C5%9Fikta%C5%9F_Logo_BJK.svg.png",
  "celtic": "https://upload.wikimedia.org/wikipedia/fr/thumb/1/1b/Celtic_FC_Logo.svg/1200px-Celtic_FC_Logo.svg.png",
  "celticglasgow": "https://upload.wikimedia.org/wikipedia/fr/thumb/1/1b/Celtic_FC_Logo.svg/1200px-Celtic_FC_Logo.svg.png",
  "rangers": "https://upload.wikimedia.org/wikipedia/fr/thumb/d/d3/Rangers_FC.svg/1200px-Rangers_FC.svg.png",
  "riverplate": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Escudo_del_C_A_River_Plate.svg/1200px-Escudo_del_C_A_River_Plate.svg.png",
  "bocajuniors": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Boca_Juniors_logo18.svg/1200px-Boca_Juniors_logo18.svg.png",
  "flamengo": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Flamengo_braz_logo.svg/1200px-Flamengo_braz_logo.svg.png",
  "palmeiras": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Palmeiras_logo.svg/1200px-Palmeiras_logo.svg.png",
};

export const FALLBACK_MATCHES: Match[] = [
  { 
    id: 'm1', 
    homeTeam: { id: 'psg', name: 'Paris Saint-Germain', shortName: 'PSG', league: 'Ligue 1', logoUrl: REAL_TEAM_LOGOS.psg },
    awayTeam: { id: 'om', name: 'Olympique de Marseille', shortName: 'OM', league: 'Ligue 1', logoUrl: REAL_TEAM_LOGOS.om },
    date: 'Aujourd\'hui', 
    time: '21:00', 
    league: 'Ligue 1' 
  },
  { 
    id: 'm2', 
    homeTeam: { id: 'real', name: 'Real Madrid', shortName: 'RMA', league: 'La Liga', logoUrl: REAL_TEAM_LOGOS.real },
    awayTeam: { id: 'barca', name: 'FC Barcelona', shortName: 'FCB', league: 'La Liga', logoUrl: REAL_TEAM_LOGOS.barca },
    date: 'Aujourd\'hui', 
    time: '20:45', 
    league: 'La Liga' 
  },
  { 
    id: 'm3', 
    homeTeam: { id: 'city', name: 'Manchester City', shortName: 'MCI', league: 'Premier League', logoUrl: REAL_TEAM_LOGOS.mancity },
    awayTeam: { id: 'liv', name: 'Liverpool FC', shortName: 'LIV', league: 'Premier League', logoUrl: REAL_TEAM_LOGOS.liverpool },
    date: 'Aujourd\'hui', 
    time: '17:30', 
    league: 'Premier League' 
  },
  { 
    id: 'm4', 
    homeTeam: { id: 'bayern', name: 'Bayern Munich', shortName: 'BAY', league: 'Bundesliga', logoUrl: REAL_TEAM_LOGOS.bayern },
    awayTeam: { id: 'dortmund', name: 'Borussia Dortmund', shortName: 'BVB', league: 'Bundesliga', logoUrl: REAL_TEAM_LOGOS.dortmund },
    date: 'Aujourd\'hui', 
    time: '18:30', 
    league: 'Bundesliga' 
  }
];